### ISSUE TITLE
Rapidvideo

### ISSUE THREAD

**Issue by bjgood** [doko-desuka/doko.repository#8] opened 2019-02-17 20:02 UTC
Hey doko,
I don't know if it's temporary or not but rapidvideo (resolveurl) is not giving any working links for any source today. If you get a chance see if you notice the same. 

Have a good one. :).

**Comment by doko-desuka** [comment] 2019-02-17 21:57
Hi @bjgood, I also wanted to ask you: is "Watchcartoononline dot io" still using that Google captcha on its videos?

As for Rapidvideo, it's a great source and I remember watching lots of movies with it, but my ISP has blocked access to it, as well as Vidoza and Streamango, possibly others.  
I know that it's blocked by my ISP because if I use a proxy through another ISP (even in my own country), then I can access it -- but the proxy severely slows down any access to it of course. So there isn't much interest for me in looking into it, unfortunately.

In any case, check your Kodi log to see if there are any "File not found" resolveurl errors, in which case the link was taken down after a copyright complaint rather than the resolver that needs an update.  
I'm closing this but I'm still here listening.

**Closed by doko-desuka** 2019-02-17 21:57 UTC

**Comment by bjgood** [comment] 2019-02-17 22:39
Are you asking if WatchNixtoons is working? It's working on my end. I have encountered the Google captcha one time while visiting WatchCartoonOnline dot io. Just that one time. I went there to check if the site was up because WatchNixtoons wasn't giving any working links. Are you having trouble?

I'd hate to loose rapidvideo. It has always given such good links.

**Comment by doko-desuka** [comment] 2019-02-17 23:36
(@ watchnixtoons) no, it's because I'm fixing an old watchnixtoons2 add-on that I was working on, and if the owner decided to keep using the Google captchas (which are impossible to solve from Kodi), then it'd be a wasted effort.  
Good to know that the captchas are gone, then. And this new addon will actually help reduce traffic to their website by caching data, which the original watchnixtoons doesn't do.

I'll take a look at Rapidvideo, but having to access it through a proxy might not give out the information needed to code the resolver. I'll get back to you

**Comment by jewbmx** [comment] 2019-02-19 09:28
Rapid video has magically disappeared twice in the past week or two lol, its back in the results right now tho.

**Comment by bjgood** [comment] 2019-02-19 14:01
Rapidvideo shows up with some sources but the link doesn't play. The source plocker normally show three results during a scan...streamango, mycloud, and rapidvideo. But for the past number of days rapidvideo has not been showing. The rapidvideo site is up (I checked again just now), so the resolveurl rapidvideo plugin is broken.

You'd think more people would be concerned about all the broken plugins in resolveurl or urlresolver. 90% of most addons depend upon either to function.

**Comment by jewbmx** [comment] 2019-02-19 20:36
I think some of the issue is that most devs use dbird services and probably rarely see the ones that we see are broken lol.
Id happily fork resolveurl and try to help maintain it but dont know my way around it much

**Comment by doko-desuka** [comment] 2019-02-20 10:00
@bjgood do you actually have any Rapidvideo links handy?
I can access the site with a proxy, but I can't find any links to content. I don't think anybody is using it anymore

**Comment by bjgood** [comment] 2019-02-20 13:30
**@jewbmx** I personally don't use RD (except for a free account) nor PM. I like keeping my money in my pocket...:).

**@doko** The only thing I have is Rapidvideo's site address (https://rapidvideo.com). I don't have any links to any videos. I like rapidvideo because it has practically everything (Poirot, Miss Marple...the hard to find stuff...plus almost everything else).

Hope you can figure it out, doko.

Have a good one.

**Comment by jewbmx** [comment] 2019-02-20 14:15
`https://www.rapidvideo.com/e/FVVAD7CYC1`

**Comment by bjgood** [comment] 2019-02-20 16:00
Alright, Jewbmx. :). Maybe those two links can help doko.

Also, the source gowatchseries had a link to rapidvideo in a series I had scanned. I went to the gowatchseries website and looked that series and episode up. I went down to the rapidvideo link and clicked on it. This what came up...

Account temporarily suspended. Please contact us for more info.

The other links showing, like vidnode and streamango, worked fine.

Later...

**Comment by doko-desuka** [comment] 2019-02-21 09:14
Thanks for the links @jewbmx. I can't imagine how you found them.

**Comment by jewbmx** [comment] 2019-02-21 09:32
Was actually making a scraper when i seen my other phone flashing a email for this post asking for links lol. Just tossed one in this phones app and grabbed a second one to be safe.
